### ISSUE TITLE
Space press doesn’t change the intermediate state (Safari)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#19] opened 2017-08-30 06:56 UTC

**Comment by limonte** [comment] 2017-08-30 14:21
In can reproduce this issue in the UX-test app, but I can't reproduce it locally. Probably it was fixed in the meantime, maybe https://github.com/vaadin/vaadin-checkbox/issues/15 was the reason and it looks like https://github.com/vaadin/vaadin-checkbox/pull/23 fixes this issue also.

Revisit after merging https://github.com/vaadin/vaadin-checkbox/pull/23

**Comment by tomivirkki** [comment] 2017-08-31 07:56
worksforme also

**Comment by limonte** [comment] 2017-08-31 08:22
Most probably this is an issue in https://wc.demo.vaadin.com/vaadin-checkbox-ux-test/ Closing for now.

**Closed by limonte** 2017-08-31 08:22 UTC
Labels: bug, in progress
